
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
  namespace: hema
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: cont1
        image: 214434260312.dkr.ecr.us-east-1.amazonaws.com/sathu:48
        ports:
        - containerPort: 80
